# ==========================================
# Configuration MySQL - JFC1 Monitoring
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/jfc1_monitoring?useSSL=false&serverTimezone=Africa/Casablanca&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.generate-ddl=true

# ==========================================
# Serveur
# ==========================================
server.port=8080

# ==========================================
# Jackson
# ==========================================
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Africa/Casablanca

# ==========================================
# Logging
# ==========================================
logging.level.org.example.project_stage_backend=INFO
logging.level.org.hibernate.SQL=DEBUG


server.servlet.context-path=/api


n8n.webhook.url=https://conductor-kinship-imminent.ngrok-free.dev/webhook/jfc3-alerte


ml.service.url=http://localhost:8001



jwt.secret=CZDCDZF165515DSFZD53DFEZDF56DZC5613
jwt.expiration=86400000